name: PotionPermissions
author: MineSocket
main: net.minesocket.potionpermissions.PotionPermissions
version: 1.0
permissions:
  potionpermissions.speed.one:
    default: false
  potionpermissions.blindness.one:
    default: false
  potionpermissions.confusion.one:
    default: false
  potionpermissions.damageresistance.one:
    default: false
  potionpermissions.fastdigging.one:
    default: false
  potionpermissions.fireresistance.one:
    default: false
  potionpermissions.harm.one:
    default: false
  potionpermissions.heal.one:
    default: false
  potionpermissions.hunger.one:
    default: false
  potionpermissions.increasedamage.one:
    default: false
  potionpermissions.invisibility.one:
    default: false
  potionpermissions.jump.one:
    default: false
  potionpermissions.nightvision.one:
    default: false
  potionpermissions.poison.one:
    default: false
  potionpermissions.regeneration.one:
    default: false
  potionpermissions.slow.one:
    default: false
  potionpermissions.slowdigging.one:
    default: false
  potionpermissions.waterbreathing.one:
    default: false
  potionpermissions.wither.one:
    default: false
  potionpermissions.weakness.one:
    default: false
  potionpermissions.speed.two:
    default: false
  potionpermissions.blindness.two:
    default: false
  potionpermissions.confusion.two:
    default: false
  potionpermissions.damageresistance.two:
    default: false
  potionpermissions.fastdigging.two:
    default: false
  potionpermissions.fireresistance.two:
    default: false
  potionpermissions.harm.two:
    default: false
  potionpermissions.hunger.two:
    default: false
  potionpermissions.heal.two:
    default: false
  potionpermissions.increasedamage.two:
    default: false
  potionpermissions.invisibility.two:
    default: false
  potionpermissions.jump.two:
    default: false
  potionpermissions.nightvision.two:
    default: false
  potionpermissions.poison.two:
    default: false
  potionpermissions.regeneration.two:
    default: false
  potionpermissions.slow.two:
    default: false
  potionpermissions.slowdigging.two:
    default: false
  potionpermissions.waterbreathing.two:
    default: false
  potionpermissions.wither.two:
    default: false
  potionpermissions.weakness.two:
    default: false
  potionpermissions.speed.three:
    default: false
  potionpermissions.blindness.three:
    default: false
  potionpermissions.confusion.three:
    default: false
  potionpermissions.damageresistance.three:
    default: false
  potionpermissions.fastdigging.three:
    default: false
  potionpermissions.fireresistance.three:
    default: false
  potionpermissions.harm.three:
    default: false
  potionpermissions.heal.three:
    default: false
  potionpermissions.hunger.three:
    default: false
  potionpermissions.increasedamage.three:
    default: false
  potionpermissions.invisibility.three:
    default: false
  potionpermissions.jump.three:
    default: false
  potionpermissions.nightvision.three:
    default: false
  potionpermissions.poison.three:
    default: false
  potionpermissions.regeneration.three:
    default: false
  potionpermissions.slow.three:
    default: false
  potionpermissions.slowdigging.three:
    default: false
  potionpermissions.waterbreathing.three:
    default: false
  potionpermissions.wither.three:
    default: false
  potionpermissions.weakness.three:
    default: false
  potionpermissions.one:
    default: false
    children:
      potionpermissions.speed.one: true
      potionpermissions.blindness.one: true
      potionpermissions.confusion.one: true
      potionpermissions.damageresistance.one: true
      potionpermissions.fastdigging.one: true
      potionpermissions.fireresistance.one: true
      potionpermissions.harm.one: true
      potionpermissions.heal.one: true
      ptoionpermissions.hunger.one: true
      potionpermissions.increasedamage.one: true
      potionpermissions.invisibility.one: true
      potionpermissions.jump.one: true
      potionpermissions.nightvision.one: true
      potionpermissions.regeneration.one: true
      potionpermissions.slow.one: true
      potionpermissions.slowdigging.one: true
      potionpermissions.waterbreathing.one: true
      potionpermissions.weakness.one: true
      potionpermissions.wither.one: true
  potionpermissions.two:
    default: false
    children:
      potionpermissions.speed.two: true
      potionpermissions.blindness.two: true
      potionpermissions.confusion.two: true
      potionpermissions.damageresistance.two: true
      potionpermissions.fastdigging.two: true
      potionpermissions.fireresistance.two: true
      potionpermissions.harm.two: true
      potionpermissions.heal.two: true
      ptoionpermissions.hunger.two: true
      potionpermissions.increasedamage.two: true
      potionpermissions.invisibility.two: true
      potionpermissions.jump.two: true
      potionpermissions.nightvision.two: true
      potionpermissions.regeneration.two: true
      potionpermissions.slow.two: true
      potionpermissions.slowdigging.two: true
      potionpermissions.waterbreathing.two: true
      potionpermissions.weakness.two: true
      potionpermissions.wither.two: true
  potionpermissions.three:
    default: false
    children:
      potionpermissions.speed.three: true
      potionpermissions.blindness.three: true
      potionpermissions.confusion.three: true
      potionpermissions.damageresistance.three: true
      potionpermissions.fastdigging.three: true
      potionpermissions.fireresistance.three: true
      potionpermissions.harm.three: true
      potionpermissions.heal.three: true
      ptoionpermissions.hunger.three: true
      potionpermissions.increasedamage.three: true
      potionpermissions.invisibility.three: true
      potionpermissions.jump.three: true
      potionpermissions.nightvision.three: true
      potionpermissions.regeneration.three: true
      potionpermissions.slow.three: true
      potionpermissions.slowdigging.three: true
      potionpermissions.waterbreathing.three: true
      potionpermissions.weakness.three: true
      potionpermissions.wither.three: true